# Generated by Django 4.1.4 on 2023-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
