# Generated by Django 4.1.4 on 2023-02-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_model_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_model',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
